# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area_id', models.CharField(max_length=128)),
                ('Area_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Org_id', models.CharField(max_length=128)),
                ('Org_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_no', models.CharField(max_length=128)),
                ('Phone_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='pwd',
            new_name='UserInfo_pwd',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user',
            new_name='UserInfo_user',
        ),
    ]
