# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JOB_LOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOC_NM', models.CharField(max_length=64)),
                ('LOC_CAP', models.IntegerField()),
                ('CUR_WRKLD', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='JOB_LOG',
            fields=[
                ('JOB_SEQ_ID', models.AutoField(primary_key=True, serialize=False)),
                ('JOB_STS', models.CharField(max_length=12)),
                ('JOB_NM', models.CharField(max_length=128)),
                ('DATA_PRD', models.CharField(max_length=10)),
                ('ACT_ST_DT', models.CharField(max_length=10, null=True)),
                ('ACT_ST_TM', models.CharField(max_length=8, null=True)),
                ('ACT_ED_DT', models.CharField(max_length=10, null=True)),
                ('ACT_ED_TM', models.CharField(max_length=8, null=True)),
                ('JOB_LG', models.CharField(max_length=24, null=True)),
                ('RW_RD', models.IntegerField(null=True)),
                ('RW_IST', models.IntegerField(null=True)),
                ('RW_UPT', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JOB_METADATA',
            fields=[
                ('JOB_ID', models.AutoField(primary_key=True, serialize=False)),
                ('JOB_NM', models.CharField(max_length=128)),
                ('SCHD_PERIOD', models.CharField(max_length=12)),
                ('JOB_TP', models.CharField(max_length=15)),
                ('LOCATION', models.CharField(max_length=255)),
                ('JOBCMD', models.CharField(max_length=255)),
                ('PARAMS', models.CharField(max_length=255)),
                ('PRIORITY', models.CharField(max_length=255)),
                ('EST_WRKLD', models.CharField(max_length=255)),
                ('PLD_ST_DT', models.DateField()),
                ('PLD_ST_TM', models.TimeField()),
                ('EXP_ED_DT', models.DateField()),
                ('EXP_ED_TM', models.TimeField()),
                ('MTX_GRP', models.CharField(max_length=128)),
                ('NTY_PTY', models.CharField(max_length=128)),
                ('INIT_FLAG', models.CharField(max_length=2)),
                ('PPN_TSTMP', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='JOB_SEQ',
            fields=[
                ('SEQ_ID', models.AutoField(primary_key=True, serialize=False)),
                ('JOB_NM', models.CharField(max_length=128)),
                ('PRE_JOB', models.CharField(max_length=128)),
                ('SEQ_TY', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=25)),
                ('PASSWORD', models.CharField(max_length=16)),
                ('EMAIL', models.CharField(max_length=64)),
                ('MOBILE', models.CharField(default='00000000000', max_length=11)),
                ('REG_DATE', models.CharField(max_length=30)),
                ('LOGIN_DATE', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32)),
            ],
        ),
    ]
