# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_job_log_job_metadata_job_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_log',
            name='ACT_ED_DT',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='job_log',
            name='ACT_ED_TM',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='job_log',
            name='ACT_ST_DT',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='job_log',
            name='ACT_ST_TM',
            field=models.CharField(max_length=8),
        ),
    ]
