# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0005_auto_20170918_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job_log',
            options={},
        ),
        migrations.AlterModelTable(
            name='job_loc',
            table='JOB_LOC',
        ),
        migrations.AlterModelTable(
            name='job_metadata',
            table='JOB_METADATA',
        ),
        migrations.AlterModelTable(
            name='job_seq',
            table='JOB_SEQ',
        ),
    ]
