# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0006_auto_20170918_1438'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='job_loc',
            table=None,
        ),
        migrations.AlterModelTable(
            name='job_log',
            table=None,
        ),
        migrations.AlterModelTable(
            name='job_metadata',
            table=None,
        ),
        migrations.AlterModelTable(
            name='job_seq',
            table=None,
        ),
    ]
