# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0007_auto_20170923_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_NAME', models.CharField(max_length=25)),
                ('PASSWORD', models.CharField(max_length=16)),
                ('EMAIL', models.CharField(max_length=64)),
                ('REG_DATE', models.CharField(max_length=30)),
                ('LOGIN_DATE', models.CharField(max_length=30)),
            ],
        ),
    ]
