# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0008_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='PHONE',
            field=models.CharField(default='00000000000', max_length=11),
        ),
    ]
