# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0010_auto_20171003_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='USER_NAME',
            new_name='USERNAME',
        ),
    ]
