# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dbinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domainname', models.CharField(max_length=32)),
                ('tableschema', models.CharField(max_length=128)),
                ('tablename', models.CharField(max_length=128)),
                ('tabledesc', models.CharField(max_length=1024)),
                ('columnname', models.CharField(max_length=128)),
                ('columndesc', models.CharField(max_length=1024)),
                ('datatype', models.CharField(max_length=64)),
                ('columntype', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='jobinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=128)),
                ('job_type', models.CharField(max_length=128)),
                ('job_path', models.CharField(max_length=128)),
                ('job_comm', models.CharField(max_length=1024)),
                ('job_rate', models.CharField(max_length=10)),
                ('job_priority', models.CharField(max_length=10)),
                ('job_valid', models.CharField(max_length=6)),
                ('create_person', models.CharField(max_length=64)),
                ('insert_date', models.DateField(max_length=26)),
                ('update_date', models.DateField(max_length=26)),
            ],
        ),
        migrations.CreateModel(
            name='jobrun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_batch', models.DateField(max_length=26)),
                ('job_name', models.CharField(max_length=128)),
                ('job_status', models.CharField(max_length=10)),
                ('job_rate', models.CharField(max_length=10)),
                ('create_person', models.CharField(max_length=64)),
                ('start_date', models.DateField(max_length=26)),
                ('end_date', models.DateField(max_length=26)),
                ('error_count', models.CharField(max_length=26)),
                ('log_path', models.CharField(max_length=512)),
                ('insert_date', models.DateField(max_length=26)),
                ('update_date', models.DateField(max_length=26)),
            ],
        ),
        migrations.CreateModel(
            name='jobsequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=128)),
                ('pre_job_name', models.CharField(max_length=128)),
                ('insert_date', models.DateField(max_length=26)),
                ('update_date', models.DateField(max_length=26)),
            ],
        ),
    ]
