# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dbinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domainname', models.CharField(max_length=32, null=True)),
                ('tableschema', models.CharField(max_length=128, null=True)),
                ('tablename', models.CharField(max_length=128, null=True)),
                ('tabledesc', models.CharField(max_length=1024, null=True)),
                ('columnname', models.CharField(max_length=128, null=True)),
                ('columndesc', models.CharField(max_length=1024, null=True)),
                ('datatype', models.CharField(max_length=64, null=True)),
                ('columntype', models.CharField(max_length=1024, null=True)),
                ('createtime', models.CharField(max_length=26, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='jobinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=128, null=True)),
                ('job_type', models.CharField(max_length=128, null=True)),
                ('job_path', models.CharField(max_length=128, null=True)),
                ('job_comm', models.CharField(max_length=1024, null=True)),
                ('job_rate', models.CharField(max_length=10, null=True)),
                ('job_priority', models.CharField(max_length=10, null=True)),
                ('job_valid', models.CharField(max_length=6, null=True)),
                ('create_person', models.CharField(max_length=64, null=True)),
                ('insert_date', models.DateField(max_length=26, null=True)),
                ('update_date', models.DateField(max_length=26, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='jobrun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_batch', models.DateField(max_length=26, null=True)),
                ('job_name', models.CharField(max_length=128, null=True)),
                ('job_status', models.CharField(max_length=10, null=True)),
                ('job_rate', models.CharField(max_length=10, null=True)),
                ('create_person', models.CharField(max_length=64, null=True)),
                ('start_date', models.DateField(max_length=26, null=True)),
                ('end_date', models.DateField(max_length=26, null=True)),
                ('error_count', models.CharField(max_length=26, null=True)),
                ('log_path', models.CharField(max_length=512, null=True)),
                ('insert_date', models.DateField(max_length=26, null=True)),
                ('update_date', models.DateField(max_length=26, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='jobsequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=128, null=True)),
                ('pre_job_name', models.CharField(max_length=128, null=True)),
                ('insert_date', models.DateField(max_length=26, null=True)),
                ('update_date', models.DateField(max_length=26, null=True)),
            ],
        ),
    ]
