# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='host',
            table=None,
        ),
    ]
