# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20170919_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('r_host_app', models.ManyToManyField(to='app01.Host')),
            ],
        ),
    ]
